// 2. Each new term in the Fibonacci sequence is generated by 
//adding the previous two terms. 
//By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values 
//do not exceed four million, find the sum of the even-valued terms.

function prob2( input ){
var j = 1;
var k;
var fibSum = 0;

for (i = 1; i<=input; i= k) {
    k= i+j;
    j= i;
    if(i%2 === 0) {
        fibSum += i;
    }
}
    solution2.innerHTML = fibSum;
}