# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4a70b3f45108bfe5867e15ba23e86852209c259e6e54d6d2268a9b6ab6ad67157b512dfd67a1f4f636cdaad76c76dc72f1d772c595883f869effe0c05bfad1b

test:
  secret_key_base: 2730e0362f5b1b44f5e40dcd0ab38997535e53f1224f3fe2154cfa375800ca1428192a1cbf5c3d36720ea46fd8a58d6581f039dc7ba21e5a4827eca4117f1762

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
